version: '3'
services:
  keyrock:
    container_name: fiware/idm
    build: .
    ports:
      - '3000:3000'
    environment:
      - MYSQL_HOST='192.168.1.42'
      - MYSQL_PASS='root'
      - MYSQL_USERNAME='root'
      - MYSQL_DB='bd'
      - MYSQL_PORT='3306'
      - DEBUG=idm:*
    volumes:
      - ./config.js:/opt/fiware-idm/config.js



